"""Emit the skeleton of a new connector mapper.

    python -m codegeneration template <provider> [vertical]

Output lands in `generated/<provider>/<vertical>_mapper_template.py`, committed like the
client so its diffs are reviewable, and regenerated by `codegeneration client` so it never
drifts from `paths.yaml`. Copy it to `connectors/<provider>/<vertical>_mapper.py` and fill
in the decisions; nothing imports the template, and nothing should.

What it generates is everything with no decisions in it: the five section banners in
order, the imports, and the endpoint class fully wired from `paths.yaml` — one method
per Chift contract method, each a provider call and a mapper call.

What it deliberately leaves empty is the mapper itself. A skeleton listing every Chift
field would guarantee coverage, but whoever fills it — a person in a hurry or an LLM —
fills every hole with something plausible, turning a loud omission into a quiet wrong
value. `python -m codegeneration check` gives the same guarantee from the other end:
it fails on any Chift field neither assigned nor declared in `UNMAPPED`, and it cannot
be satisfied by writing something that merely looks right.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

from codegeneration.generate_context import _config, _vendor_spec

ROOT = Path(__file__).resolve().parents[1]

# Chift contract method -> the provider operation that serves it, by resource and verb.
# Only the pairing is guessed; a name this cannot resolve is emitted as a TODO.
CONTRACT = {
    "get_contact": ("customer", "get"),
    "list_contacts": ("customer", "list"),
    "create_contact": ("customer", "create"),
    "get_invoice": ("invoice", "get"),
    "list_invoices": ("invoice", "list"),
    "create_invoice": ("invoice", "create"),
}

HEAD = '''"""
Chift {vertical} mapper against {Provider}.

Generated client fetches provider JSON; this maps into chift.models.

Provenance:
  Procedure: AGENTS.md § Adding a connector
  Contract: python -m codegeneration contract {provider} <operationId>
  Skeleton: python -m codegeneration template {provider}

Every mapping decision below is written by a human or an LLM and then reviewed.
`python -m codegeneration check {provider}` enforces the structure and the coverage.
"""

from __future__ import annotations

from typing import Any

from chift import models as chift
from chift.invoicing_connector import InvoicingConnector
from connectors.{provider}.config import get_settings
from generated.{provider}.client import {client_class}


# Chift fields {Provider} does not carry. `check` fails on any target field that is
# neither assigned nor listed here, so an omission must be a decision, not an oversight.
UNMAPPED: dict[str, set[str]] = {{}}


{rule}
# Constants — every provider value Chift maps, stated explicitly and exhaustively.
{rule}


# One UPPER_CASE table per provider enum Chift maps. Exhaustive over the published
# values, no defaults — an unmapped value must raise, never become a plausible one.


{rule}
# Utilities — mechanical helpers. No Chift semantics, no provider judgement.
{rule}


# Money scaling, date trimming. Every name `_`-prefixed, and none may mention chift.* —
# a helper that builds a Chift object is a mapper and belongs in the section below.


{rule}
# Mapper — provider JSON <-> Chift models. Every semantic decision is here.
{rule}
#
# Signatures only: the fields are the decisions, and `check` fails until each one is
# assigned or declared in UNMAPPED. Sub-mappers (to_address, to_line, ...) go here too,
# each pair directly above the pair that uses it.


def to_contact(data: dict[str, Any]) -> chift.ContactItemOut:
    """Map one {provider} customer to Chift."""
    raise NotImplementedError


def from_contact(body: chift.ContactItemIn) -> dict[str, Any]:
    """Chift ContactItemIn -> {provider} customer. Inverse of `to_contact`."""
    raise NotImplementedError


def to_invoice(data: dict[str, Any]) -> chift.InvoiceItemOut:
    """Map one {provider} invoice to Chift."""
    raise NotImplementedError


def from_invoice(body: chift.InvoiceItemIn) -> dict[str, Any]:
    """Chift InvoiceItemIn -> {provider} invoice. Inverse of `to_invoice`."""
    raise NotImplementedError


{rule}
# Pagination — provider cursors -> one numbered Chift page.
{rule}


def page_via_cursor(fetch, *, page: int, size: int, map_item, **query):
    """Reconstruct one numbered Chift page from the provider's paging scheme."""
    raise NotImplementedError


{rule}
# Endpoint — the Chift contract, wiring provider calls to the mappers.
{rule}


# Provider HTTP failures propagate to the single translator in chift.errors.
class {Provider}{Vertical}Connector(InvoicingConnector):
    provider = "{provider}"

    @classmethod
    def from_env(cls) -> {Provider}{Vertical}Connector:
        """Credentials live in connectors/{provider}/config.py."""
        return cls()

    def __init__(self, client: {client_class} | None = None) -> None:
        # An injected client (tests, a fake) must not require a .env.
        if client is None:
            settings = get_settings()
            client = {client_class}(settings.base_url, settings.api_key)
        self.client = client
'''

METHOD = '''
    def {name}(self{args}) -> {returns}:
        """{doc}"""
        {body}
'''


def _operations(spec: dict, selected: set[tuple[str, str]]) -> dict[str, str]:
    """(resource, verb) -> client method name, for the operations this connector calls."""
    found = {}
    for path, item in spec["paths"].items():
        for method, op in item.items():
            if (path, method) not in selected or not isinstance(op, dict):
                continue
            operation_id = op.get("operationId") or ""
            snake = "".join(
                f"_{c.lower()}" if c.isupper() else c for c in operation_id
            ).lstrip("_")
            verb = "list" if snake.startswith("list") else snake.split("_")[0]
            resource = snake.split("_", 1)[-1].rstrip("s")
            found[(resource, verb)] = snake
    return found


def template(provider: str, vertical: str = "invoicing") -> str:
    """Return the skeleton for one provider's mapper."""
    from codegeneration.generate_context import selected

    config = _config(provider)
    spec = _vendor_spec(provider)
    client_class = config.get("client_class", f"{provider.title()}Client")
    ops = _operations(spec, selected(provider))
    # Chift's contact is most providers' customer; try both before giving up.
    alias = {"contact": ("contact", "customer"), "invoice": ("invoice", "invoice")}

    body = HEAD.format(
        provider=provider,
        Provider=provider.title(),
        vertical=vertical,
        Vertical=vertical.title(),
        client_class=client_class,
        rule="# " + "-" * 76,
    )
    for name, (resource, verb) in CONTRACT.items():
        call = next(
            (ops[(r, verb)] for r in alias.get(resource, (resource,)) if (r, verb) in ops),
            None,
        )
        chift_type = "ContactItemOut" if "contact" in name else "InvoiceItemOut"
        mapper = "to_contact" if "contact" in name else "to_invoice"
        inverse = "from_contact" if "contact" in name else "from_invoice"
        if call is None:
            args, returns, doc, code = "", "None", f"TODO: {name}", "raise NotImplementedError"
        elif verb == "get":
            args, returns = f", {resource}_id: str", f"chift.{chift_type}"
            doc = f"Retrieve and map one {provider} {resource}."
            code = f"return {mapper}(self.client.{call}({resource}_id))"
        elif verb == "list":
            args, returns = ", *, page: int = 1, size: int = 50", f"chift.ChiftPage[chift.{chift_type}]"
            doc = f"Retrieve and map one numbered page of {provider} {resource}s."
            code = (
                f"return page_via_cursor(\n"
                f"            self.client.{call}, page=page, size=size, map_item={mapper}\n"
                f"        )"
            )
        else:
            in_type = "ContactItemIn" if "contact" in name else "InvoiceItemIn"
            args, returns = f", body: chift.{in_type}", f"chift.{chift_type}"
            doc = f"Create and map one {provider} {resource}."
            code = f"return {mapper}(self.client.{call}({inverse}(body)))"
        body += METHOD.format(name=name, args=args, returns=returns, doc=doc, body=code)
    return body


def write(provider: str, vertical: str = "invoicing") -> Path:
    """Write the skeleton beside the generated client and return its path."""
    out = ROOT / "generated" / provider
    out.mkdir(parents=True, exist_ok=True)
    path = out / f"{vertical}_mapper_template.py"
    path.write_text(template(provider, vertical))
    # Emit lint-clean output: regenerating must never dirty the tree.
    subprocess.run(["ruff", "check", "--fix", "-q", str(path)], check=False)
    subprocess.run(["ruff", "format", "-q", str(path)], check=True)
    return path


def main(argv: list[str] | None = None) -> None:
    """Write one provider's mapper skeleton."""
    args = list(argv if argv is not None else sys.argv[1:])
    if not 1 <= len(args) <= 2:
        raise SystemExit("usage: python -m codegeneration template <provider> [vertical]")
    path = write(*args)
    print(f"wrote {path.relative_to(ROOT)}")
