"""Step 1, deterministic: emit a thin httpx client for the operations the agent selected.

One method per operation, the spec's own auth header, JSON in, dictionaries out. No provider models: responses
stay the JSON the provider actually returned. Same inputs, same file, byte for byte.

Why hand-rolled rather than openapi-python-client or openapi-generator: those emit typed models
for every schema, thousands of classes for a spec as `anyOf`-heavy as Hyperline's, and choke on
parts of it. We only need the operations the connector calls. The client still earns its place:
the LLM can only call methods that exist in the spec, so it cannot invent an endpoint.
"""

from __future__ import annotations

import ast
import re
import textwrap

HEADER = '''"""Generated by `python -m chift.generator` from {spec}. Do not edit."""

from __future__ import annotations

import time
from urllib.parse import quote

import httpx


def retry_after(response: httpx.Response, attempt: int) -> float:
    """Seconds a 429 asks to wait: its Retry-After in seconds, else 2, 4, 8; at most 30."""
    try:
        return min(float(response.headers.get("Retry-After", "")), 30.0)
    except ValueError:
        return float(2 ** (attempt + 1))


class Client:
    def __init__(self, base_url: str, token: str, timeout: float = 90):
        """Connect to the provider with its credential ({scheme}) and a request timeout."""
        self.http = httpx.Client(
            base_url=base_url, timeout=timeout, headers={{{header!r}: {prefix!r} + token}}
        )

    def _request(self, method: str, path: str, query: dict | None = None, body: dict | None = None) -> dict:
        """Make one request and return JSON, raising for provider HTTP failures.

        A 429 is the provider asking to slow down: wait as long as it says (at most 30 s), up to
        three times. Any other failure raises at once.
        """
        params = {{k: v for k, v in (query or {{}}).items() if v is not None}}
        for attempt in range(4):
            response = self.http.request(method, path, params=params, json=body)
            if response.status_code != 429 or attempt == 3:
                break
            time.sleep(retry_after(response, attempt))
        response.raise_for_status()
        return response.json() if response.content else {{}}

'''


def auth(spec: dict) -> tuple[str, str, str]:
    """(header, value prefix, description) for the spec's credential; unsupported schemes fail.

    Covers what most invoicing APIs use: a bearer token, or an API key in a header.
    """
    for scheme in (spec.get("components", {}).get("securitySchemes") or {}).values():
        if scheme.get("type") == "http" and scheme.get("scheme", "").lower() == "bearer":
            return "Authorization", "Bearer ", "bearer token"
        if scheme.get("type") == "apiKey" and scheme.get("in") == "header":
            return scheme["name"], "", f"API key in the {scheme['name']} header"
    kinds = [s.get("type") for s in (spec.get("components", {}).get("securitySchemes") or {}).values()]
    raise ValueError(f"unsupported authentication {kinds or 'none declared'}: only bearer tokens "
                     "and header API keys are implemented")


def snake(name: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "_", name).lower()


def method(path: str, verb: str, op: dict) -> str:
    params = op.get("parameters", [])
    path_params = [p["name"] for p in params if p["in"] == "path"]
    query = [p for p in params if p["in"] == "query"]
    args = ["self"] + [f"{name}: str" for name in path_params]
    has_body = "requestBody" in op
    if has_body:
        args.append("body: dict")
    if query:  # list endpoints declare dozens of filters: pass any as keywords, documented below
        args.append("**query")
    doc = [f"{verb.upper()} {path}", ""]
    if op.get("summary"):
        doc += [op["summary"].strip(), ""]
    undocumented = []
    for p in query:
        schema = p.get("schema", {})
        enum = next((s["enum"] for s in [schema, *schema.get("anyOf", [])] if "enum" in s), None)
        note = " ".join((p.get("description") or schema.get("description") or "").split())
        if enum:
            note = f"{note} One of {enum}.".strip()
        if "default" in schema:
            note = f"{note} Default {schema['default']!r}.".strip()
        if note:
            doc.append(f"{p['name']}: {note}")
        else:
            undocumented.append(p["name"])
    if undocumented:
        doc += ["", *textwrap.wrap("Also: " + ", ".join(undocumented) + ".", 88)]
    url = re.sub(r"{(\w+)}", r"{quote(\1, safe='')}", path)
    url = f'f"{url}"' if path_params else f'"{url}"'
    call_query = ", query" if query else ""
    if has_body:
        call_query += ", body=body" if query else ", None, body"
    body = "\n".join(f"        {line}".rstrip() for line in doc).strip()
    signature = ",\n        ".join(args)
    return (
        f"\n    def {snake(op['operationId'])}(\n        {signature},\n    ) -> dict:\n"
        f'        """{body}\n        """\n'
        f'        return self._request("{verb.upper()}", {url}{call_query})\n'
    )


def generate(spec: dict, spec_path: str, operation_ids: list[str]) -> str:
    """The client module's source for `operation_ids`, sorted by name. Unknown IDs fail the run."""
    found = {}
    for path, item in spec["paths"].items():
        for verb, op in item.items():
            if isinstance(op, dict) and op.get("operationId") in operation_ids:
                found[op["operationId"]] = method(path, verb, op)
    missing = set(operation_ids) - set(found)
    if missing:
        raise ValueError(f"operations not in {spec_path}: {sorted(missing)}")
    header_name, prefix, scheme = auth(spec)
    header = HEADER.format(spec=spec_path, header=header_name, prefix=prefix, scheme=scheme)
    source = header + "".join(found[op] for op in sorted(found))
    client = next(n for n in ast.parse(source).body if isinstance(n, ast.ClassDef) and n.name == "Client")
    methods = {n.name for n in client.body if isinstance(n, ast.FunctionDef)}
    missing = {snake(op) for op in operation_ids} - methods
    if missing:  # guards the template: every operation must land on Client
        raise ValueError(f"generated Client lacks methods {sorted(missing)}")
    return source
