# AUTO-GENERATED by connector-gen — do not edit manually
# Raw HTTP methods to call Hyperline, one per OpenAPI endpoint.
from typing import Any

import httpx

from chift_api.config import Settings


class HyperlineAPIError(Exception):
    def __init__(self, status_code: int, message: str, payload: dict[str, Any] | None = None):
        self.status_code = status_code
        self.message = message
        self.payload = payload or {}
        super().__init__(message)


class HyperlineClientGenerated:
    def __init__(self, settings: Settings, client: httpx.Client | None = None):
        self._client = client or httpx.Client(
            base_url=settings.hyperline_base_url,
            headers={"Authorization": f"Bearer {settings.hyperline_api_key}"},
            timeout=30.0,
        )

    def close(self) -> None:
        self._client.close()

    def get_customer_v2(self, id: str) -> dict[str, Any]:
        """Get customer"""
        return self._request("GET", f"/v2/customers/{id}", params=None)

    def list_customers_v2(self, *, limit: Any | None = None, cursor: Any | None = None, include_total: Any | None = None, order: Any | None = None, sort: Any | None = None, name: Any | None = None, name__not: Any | None = None, name__isNull: Any | None = None, **extra_query: Any) -> dict[str, Any]:
        """List customers"""
        params = {
            k: v for k, v in {"limit": limit, "cursor": cursor, "include_total": include_total, "order": order, "sort": sort, "name": name, "name__not": name__not, "name__isNull": name__isNull, **extra_query}.items()
            if v is not None
        }
        return self._request("GET", f"/v2/customers", params=params or None)

    def get_invoice_v1(self, id: str) -> dict[str, Any]:
        """Get invoice"""
        return self._request("GET", f"/v1/invoices/{id}", params=None)

    def list_invoices_v1(self, *, take: Any | None = None, skip: Any | None = None, order: Any | None = None, sort: Any | None = None, type: Any | None = None, type__in: Any | None = None, status: Any | None = None, status__in: Any | None = None, **extra_query: Any) -> dict[str, Any]:
        """List invoices"""
        params = {
            k: v for k, v in {"take": take, "skip": skip, "order": order, "sort": sort, "type": type, "type__in": type__in, "status": status, "status__in": status__in, **extra_query}.items()
            if v is not None
        }
        return self._request("GET", f"/v1/invoices", params=params or None)

    def create_customer_v1(self, *, body: dict[str, Any] | None = None) -> dict[str, Any]:
        """Create customer"""
        return self._request("POST", f"/v1/customers", params=None, json=body)

    def create_invoice_v1(self, *, body: dict[str, Any] | None = None) -> dict[str, Any]:
        """Create invoice"""
        return self._request("POST", f"/v1/invoices", params=None, json=body)

    def _request(
        self,
        method: str,
        path: str,
        *,
        params: dict[str, Any] | None = None,
        json: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        response = self._client.request(method, path, params=params, json=json)

        if response.status_code == 404:
            payload = _safe_json(response)
            raise HyperlineAPIError(404, payload.get("message", "Resource not found"), payload)

        if response.status_code >= 400:
            payload = _safe_json(response)
            raise HyperlineAPIError(response.status_code, payload.get("message", response.text), payload)

        return response.json()


def _safe_json(response: httpx.Response) -> dict[str, Any]:
    try:
        data = response.json()
        return data if isinstance(data, dict) else {}
    except ValueError:
        return {}
