# OpenAPI → connector client codegen. CLI: `connector-gen generate hyperline`

from __future__ import annotations

import argparse
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

CONNECTORS_DIR = Path(__file__).resolve().parent
_PATH_PARAM = re.compile(r"\{([^}]+)\}")


@dataclass(frozen=True)
class OperationSpec:
    name: str
    method: str
    path: str


def load_openapi(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return json.load(handle)


def load_generator_config(path: Path) -> dict[str, Any]:
    with path.open(encoding="utf-8") as handle:
        return yaml.safe_load(handle)


def generate_client_code(spec: dict[str, Any], operations: list[OperationSpec], *, class_name: str) -> str:
    methods = [
        _render_method(operation, _get_operation(spec, operation.method, operation.path))
        for operation in operations
    ]
    body = "\n\n".join(methods)
    return f'''# AUTO-GENERATED by connector-gen — do not edit manually
# Raw HTTP methods to call Hyperline, one per OpenAPI endpoint.
from typing import Any

import httpx

from chift_api.config import Settings


class HyperlineAPIError(Exception):
    def __init__(self, status_code: int, message: str, payload: dict[str, Any] | None = None):
        self.status_code = status_code
        self.message = message
        self.payload = payload or {{}}
        super().__init__(message)


class {class_name}:
    def __init__(self, settings: Settings, client: httpx.Client | None = None):
        self._client = client or httpx.Client(
            base_url=settings.hyperline_base_url,
            headers={{"Authorization": f"Bearer {{settings.hyperline_api_key}}"}},
            timeout=30.0,
        )

    def close(self) -> None:
        self._client.close()

{body}

    def _request(
        self,
        method: str,
        path: str,
        *,
        params: dict[str, Any] | None = None,
        json: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        response = self._client.request(method, path, params=params, json=json)

        if response.status_code == 404:
            payload = _safe_json(response)
            raise HyperlineAPIError(404, payload.get("message", "Resource not found"), payload)

        if response.status_code >= 400:
            payload = _safe_json(response)
            raise HyperlineAPIError(response.status_code, payload.get("message", response.text), payload)

        return response.json()


def _safe_json(response: httpx.Response) -> dict[str, Any]:
    try:
        data = response.json()
        return data if isinstance(data, dict) else {{}}
    except ValueError:
        return {{}}
'''


def generate_from_config(config_path: Path) -> Path:
    connector_dir = config_path.parent
    config = load_generator_config(config_path)
    openapi_path = connector_dir / config["openapi"]
    output_path = connector_dir / config["output"]
    class_name = config.get("class_name", "GeneratedClient")

    spec = load_openapi(openapi_path)
    operations = [
        OperationSpec(name=item["name"], method=item["method"].lower(), path=item["path"])
        for item in config["operations"]
    ]

    output_path.write_text(generate_client_code(spec, operations, class_name=class_name), encoding="utf-8")
    return output_path


def _get_operation(spec: dict[str, Any], method: str, path: str) -> dict[str, Any]:
    try:
        return spec["paths"][path][method]
    except KeyError as exc:
        raise ValueError(f"Operation not found in OpenAPI: {method.upper()} {path}") from exc


def _render_method(operation: OperationSpec, raw: dict[str, Any]) -> str:
    path_params = _PATH_PARAM.findall(operation.path)
    query_params = [
        param["name"]
        for param in raw.get("parameters", [])
        if param.get("in") == "query" and "name" in param
    ]
    has_body = "requestBody" in raw

    args = ["self", *[f"{_safe_name(name)}: str" for name in path_params]]
    if query_params:
        args.append("*")
        args.extend(f"{_safe_name(name)}: Any | None = None" for name in query_params[:8])
        args.append("**extra_query: Any")
    elif has_body:
        args.append("*")
    if has_body:
        args.append("body: dict[str, Any] | None = None")

    path_build = operation.path
    for name in path_params:
        path_build = path_build.replace("{" + name + "}", "{" + _safe_name(name) + "}")

    lines = [
        f"    def {operation.name}({', '.join(args)}) -> dict[str, Any]:",
        f'        """{raw.get("summary", operation.name)}"""',
    ]

    if query_params:
        keys = query_params[:8]
        mapping = ", ".join(f'"{name}": {_safe_name(name)}' for name in keys)
        lines.extend(
            [
                "        params = {",
                f"            k: v for k, v in {{{mapping}, **extra_query}}.items()",
                "            if v is not None",
                "        }",
            ]
        )
        params_expr = "params or None"
    else:
        params_expr = "None"

    if has_body:
        lines.append(
            f'        return self._request("{operation.method.upper()}", f"{path_build}", params={params_expr}, json=body)'
        )
    else:
        lines.append(
            f'        return self._request("{operation.method.upper()}", f"{path_build}", params={params_expr})'
        )

    return "\n".join(lines)


def _safe_name(name: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_]", "_", name)


def main() -> None:
    parser = argparse.ArgumentParser(description="Generate connector code from OpenAPI")
    parser.add_argument("command", choices=["generate"])
    parser.add_argument("connector", help="Connector name (e.g. hyperline)")
    args = parser.parse_args()

    config_path = CONNECTORS_DIR / args.connector / "generator.yaml"
    if not config_path.exists():
        raise SystemExit(f"Config not found: {config_path}")

    output = generate_from_config(config_path)
    print(f"Generated {output}")


if __name__ == "__main__":
    main()
